[package]
name = "snake"
version = "0.1.0"
authors = ["Stewart Allen <allenstew@gmail.com>"]
edition = "2018"

[dependencies]
piston = "0.39.0"
piston2d-graphics = "0.28.0"
piston_window = "0.85.0"
rand = "0.6.1"